### PR TITLE
updated the Inferno implementations

### PR DESCRIPTION
**Pull request by trueadm**
I noticed that the `color-picker` had a funky Inferno implementation, this updates it. Runs a lot better locally for me now. I also opted to use `noNormalize` in places as an optimization technique where I knew it was safe.

### CODE REVIEW

**Comment by patrick-steele-idem** [comment]
Hey Dominic, thanks for reviewing the benchmarks and thank you for the PR. It's interesting to see how the optimization flags impacted the performance (putting Marko and Inferno mostly on par with a very slight edge for Inferno in latest Google Chrome from my quick testing). That also gives me some ideas on how we can further optimize the Marko VDOM since we are also do tag name normalization (assuming that is what `noNormalize` means). With that said, I'm kind of torn on this one... 

I definitely have no objections with your changes to switch to the functional component for `Footer.jsx` and the change to make use of `linkEvent`. 👍 

I do, however, have objections with the changes to introduce the undocumented `noNormalize` and `hasKeyedChildren` attributes (at least I could not find any documentation, but please correct me if I am wrong). To me, this feels like an attempt to game the benchmark since it would be outside standard practice of Inferno users. Even if those flags were documented, I feel like very few, if any, devs would use them. If the Inferno JS transform applied these optimizations automatically then I would have zero objections.

Removing the `noNormalize` and `hasKeyedChildren` attributes keeps the results roughly the same as what we published (although I would need to test further in other browsers).

Is it okay if I merge your change but remove the `noNormalize` and `hasKeyedChildren` attribute. Does that seem fair?

**Comment by trueadm** [comment]
@patrick-steele-idem I don't work on Inferno like I used to, but I did state that we should document these parts – I can get the team to prioritise that. `noNormalize` stops Inferno from recursively scanning all children and making them React compatible, as most people coming to Inferno will simply switch their React apps over. Thus why it's quite slow, it's basically a mini compatibility layer.

Inferno never used to do this, thus why in benchmarks from before Christmas, Inferno was about 2-3x faster than it currently is now, simply because of normalization (it's got nothing to do with DOM nodes or even the DOM). I expect it can be removed from Inferno, there was already a task to do this, but given I now work full-time on the React – I haven't been able to work on this task.

**Comment by patrick-steele-idem** [comment]
Thanks for the details @trueadm.

I'm going to merge your changes, but remove the undocumented `noNormalize` and `hasKeyedChildren` attributes that you added. I am happy to update the results once the Inferno team makes changes to remove the normalization from Inferno so please encourage them to open an issue. I'm going to hold off on updating results right now since it is a tedious process to update the results since I have to manually run the benchmark in all browsers and devices. As I mentioned above, your other changes that I will merge in seemed to have no noticeable impact on the benchmark.

**Comment by trueadm** [comment]
@patrick-steele-idem That's fair. Hopefully, @havunen can pick up this in the future and get this change made. Thanks!

**Comment by Havunen** [comment]
As per request, I have improved docs.

https://infernojs.org/docs/guides/benefits/list-rendering
https://infernojs.org/docs/guides/optimisations

**Comment by patrick-steele-idem** [comment]
Hey @Havunen, the docs look good, but I still don't think it be normal practice to add those special attributes that provide hints to Inferno. For this benchmark, I only want to measure the performance  without the user having to specify any special (and possibly problematic) attributes (except `key` which is critical for keyed matching). If you are able to update the Inferno babel transform to add those hints automatically based on the static code then I would have no problem updating the results. Alternatively, if normalization can be safely disabled globally then I would be fine with that as well.

**Pull request merged**
